(TeX-add-style-hook
 "appendix.mng"
 (lambda ()
   (TeX-add-symbols
    '("optpair" 1)
    '("optcast" 1)
    '("etaconv" 1)
    '("proj" 1)
    '("castup" 1)
    '("castdown" 1)
    '("subty" 4)
    '("gao" 1)
    '("intersec" 2)
    '("open" 2)
    '("letin" 3)
    '("subst" 2)
    '("transenv" 1)
    '("coerf" 1)
    '("trans" 1)
    '("modwrapper" 1)
    '("sigwrapper" 1)
    '("typeinfer" 3)
    '("ruleform" 1)
    "projk"))
 :latex)

