(TeX-add-style-hook
 "test"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-add-symbols
    '("optpair" 1)
    '("optcast" 1)
    '("etaconv" 1)
    '("proj" 1)
    '("castup" 1)
    '("castdown" 1)
    '("subtyy" 5)
    '("subty" 4)
    '("intersec" 2)
    '("open" 2)
    '("letin" 3)
    '("subst" 2)
    '("transenv" 1)
    '("coerf" 1)
    '("trans" 1)
    '("modwrapper" 1)
    '("sigwrapper" 1)
    '("typeinfer" 3)
    '("ruleform" 1)
    "projk"))
 :latex)

